title: Sentry.io - Türkçe Doküman
theme: jekyll-theme-minima
author:
  name: bilalkarakollu
  email: karakollubilal@gmail.com
description: Sentry.io dokümantasyonunun Türkçe'ye uyarlanmış halidir.
social_links:
    twitter: BilalKarakollu
    github:  bilalkarakollu
    instagram:  bilalkarakollu
    medium:  bilalkarakollu
    linkedin:  bilalkarakollu

plugins:
 - jekyll-feed
 - jekyll-seo-tag